Update resolver
BBVAEngineering/ember-cli-awesome-resolver pull request #2
Opened 2017-05-30 10:46 UTC by beatrizdemiguelperez

2017-05-30 15:38 UTC, shokmaster approved these changes

2017-06-01 08:02 UTC, josex2r requested changes
Échale un ojo a los comentarios antes de mergear

2017-06-01 08:02 UTC, josex2r commented on addon/mixins/resolver.js
> +	namespaces: [],
Por defecto no se habilitan los prototipos de Ember en los addons, ¿estás segura de que no hace falta un array de Ember?

2017-06-01 08:02 UTC, josex2r commented on tests/helpers/amd.js
> +	defines: [],
Lo mismo del comentario de arriba

2017-06-01 08:02 UTC, josex2r commented on addon/utils/entries.js
> +		for (const { name }
Si puedes evita el `for ... of ...`, babel mete mucha mierda

2017-06-01 08:09 UTC, adrigzr requested changes
Tasks pending.

2017-06-01 08:09 UTC, adrigzr commented on addon/mixins/resolver.js
> +					Ember.debug(`found reopen '${entry}' for '${moduleName}'`);
Destructuring.

2017-06-01 08:09 UTC, adrigzr commented on addon/mixins/resolver.js
> +	namespaces: [],
Initialize with `null` and setup array on `init()` hook.

2017-06-01 08:09 UTC, adrigzr commented on addon/utils/entries.js
>  			of properties) {
`for-of` is slow.

2017-06-01 08:09 UTC, adrigzr commented on addon/mixins/resolver.js
>  		merge(items, this._super(type));
Remove `utils/merge` and use `Object.assign`.

2017-06-01 08:09 UTC, adrigzr commented on tests/helpers/start-app.js
> +	let attributes = Ember.merge({}, config.APP);
Use `Object.assign`.

2017-06-01 11:02 UTC, josex2r approved these changes

2017-06-01 13:17 UTC, adrigzr requested changes

2017-06-01 13:17 UTC, adrigzr commented on addon/mixins/resolver.js
> +		this.set('namespaces', A([]));
Remove the `[]`.

2017-06-01 13:17 UTC, adrigzr commented on tests/helpers/amd.js
> +	defines:  A([]),
Remove `[]`.

2017-06-01 13:28 UTC, adrigzr approved these changes

2017-06-01 13:31 UTC, merged