upgrade dependencies
BBVAEngineering/ember-cli-awesome-resolver pull request #6
Opened 2018-08-10 11:03 UTC by etarancon

2018-08-10 11:56 UTC, josex2r commented on tests/dummy/app/router.js
> +Router.map(() => {
this shouldn't be an arrow function

2018-08-16 10:35 UTC, adrigzr approved these changes

2018-08-16 10:37 UTC, adrigzr requested changes

2018-08-16 10:37 UTC, adrigzr commented on tests/unit/amd-test.js
> +	assert.notOk(requirejs.entriesfoo);
This is wrong

2018-08-16 10:41 UTC, adrigzr submitted a review, later dismissed

2018-08-16 10:56 UTC, shokmaster commented on tests/dummy/app/router.js
>  const Router = Ember.Router.extend({
`import EmberRouter from '@ember/routing/router';`

2018-08-16 10:56 UTC, shokmaster commented on tests/helpers/destroy-app.js
>  export default function destroyApp(application) {
`import { run } from '@ember/runloop';`

2018-08-16 11:04 UTC, etarancon commented on tests/helpers/destroy-app.js
>  export default function destroyApp(application) {
done

2018-08-16 11:04 UTC, etarancon commented on tests/dummy/app/router.js
>  const Router = Ember.Router.extend({
done

2018-08-16 11:08 UTC, adrigzr approved these changes

2018-08-16 12:36 UTC, merged